package dao;
// Generated Jun 22, 2021 1:56:43 PM by Hibernate Tools 5.1.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Commandes generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "commandes", catalog = "g_vente")
public class Commandes implements java.io.Serializable {

	private Integer codeCmd;
	private String client;
	private int codeArt;
	private int qteCmd;
	private Date dateCmd;

	public Commandes() {
	}

	public Commandes(String client, int codeArt, int qteCmd, Date dateCmd) {
		this.client = client;
		this.codeArt = codeArt;
		this.qteCmd = qteCmd;
		this.dateCmd = dateCmd;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "codeCMD", unique = true, nullable = false)
	public Integer getCodeCmd() {
		return this.codeCmd;
	}

	public void setCodeCmd(Integer codeCmd) {
		this.codeCmd = codeCmd;
	}

	@Column(name = "client", nullable = false, length = 20)
	public String getClient() {
		return this.client;
	}

	public void setClient(String client) {
		this.client = client;
	}

	@Column(name = "codeArt", nullable = false)
	public int getCodeArt() {
		return this.codeArt;
	}

	public void setCodeArt(int codeArt) {
		this.codeArt = codeArt;
	}

	@Column(name = "qteCMD", nullable = false)
	public int getQteCmd() {
		return this.qteCmd;
	}

	public void setQteCmd(int qteCmd) {
		this.qteCmd = qteCmd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateCMD", nullable = false, length = 10)
	public Date getDateCmd() {
		return this.dateCmd;
	}

	public void setDateCmd(Date dateCmd) {
		this.dateCmd = dateCmd;
	}

}
